### ISSUE TITLE
Import CA cert to browser

### ISSUE THREAD

**Issue by prvsousa** [google/easypki#7]
I'm trying to import CA cert for browser, the step:

> Import CA+chain.crt in your favorite browser.
of the README.md  of the example of ClientAuth.

However i got the error on Chrome:

```
The Private Key for this Client Certificate is missing or invalid.
```

**Comment by jeremy-clerc** [comment]
What OS are your using ?

I generated them on a Ubuntu server, and imported in chrome on a MacOS with no error.

One thing I discovered as I was also trying to import the p12 file is that the MacOS keychain relies on the file extension, it has to be .p12. But no problem with the CA+chain.crt.

**Comment by jeremy-clerc** [comment]
Also if you are on MacOS, make sure to select the System keychain (on the left) before importing.

**Comment by jeremy-clerc** [comment]
Just retried by generating everything directly on MacOS and no problem.
